{
 "title": "Edge-LB",
 "description": "Kafka resource usage and throughput",
 "tags": [
  "edge-lb",
  "haproxy"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "task_name", "label": "Pool Name", "query": "label_values(task_name)" },
   { "name": "rate_interval", "label": "Rate Interval", "query": "10s,30s,1m,2m,5m,10m" }
  ]
 },
 "panels": [
  { "title": "Overall Load Balancer Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pool Overview",
   "type": "table",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by (service_name, host) (cpus_limit{executor_name=\"edgelb-pool\"})"
    }
   ]
  },
  {
   "title": "Pool Backends Up",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (max (haproxy_backend_up{task_name=\"$task_name\",backend!=\"stats\"} == 1) by (backend))"
    }
   ]
  },
  {
   "title": "Pool Backends Down",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (max (haproxy_backend_up{task_name=\"$task_name\",backend!=\"stats\"} == 0) by (backend))"
    }
   ]
  },
  {
   "title": "Backend Servers Up",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (max (haproxy_server_up{task_name=\"$task_name\",backend!=\"stats\"} == 1) by (server))"
    }
   ]
  },
  {
   "title": "Backend Servers Down",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (max (haproxy_server_up{task_name=\"$task_name\",backend!=\"stats\"} == 0) by (server))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "min(cpus_limit{executor_name=\"edgelb-pool\"})",
     "legendFormat": "CPU Limit"
    },
    {
     "expr": "rate(cpus_system_time_secs{executor_name=\"edgelb-pool\"}[2m]) + rate(cpus_user_time_secs{executor_name=\"edgelb-pool\"}[2m])",
     "legendFormat": "CPU Usage {{service_name}} {{ host }}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "min(mem_limit_bytes{executor_name=\"edgelb-pool\"})",
     "legendFormat": "Memory Limit"
    },
    {
     "expr": "mem_total_bytes{executor_name=\"edgelb-pool\"}",
     "legendFormat": "Memory Usage {{service_name}} {{host}}"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bytes", "label": "Disk" }
   ],
   "targets": [
    {
     "expr": "min(disk_limit_bytes{executor_name=\"edgelb-pool\"})",
     "legendFormat": "Disk Limit"
    },
    {
     "expr": "disk_used_bytes{executor_name=\"edgelb-pool\"}",
     "legendFormat": "Disk Usage {{service_name}} {{host}}"
    }
   ]
  },
  { "title": "Frontend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "HTTP Requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(haproxy_frontend_http_requests_total{task_name=\"$task_name\",frontend!=\"stats\"}[1m]))"
    }
   ]
  },
  {
   "title": "HTTP Errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(haproxy_frontend_request_errors_total{task_name=\"$task_name\",frontend!=\"stats\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total responses by HTTP code",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(haproxy_frontend_http_responses_total{task_name=\"$task_name\",frontend!=\"stats\"}) by (code)",
     "legendFormat": "Frontend {{ code }}"
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(haproxy_frontend_current_sessions{task_name=\"$task_name\",frontend!=\"stats\"}[1m]))"
    }
   ]
  },
  {
   "title": "Session Utilization",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(haproxy_frontend_current_sessions{task_name=\"$task_name\",frontend!=\"stats\"}) / sum (haproxy_frontend_limit_sessions{frontend!=\"stats\"}) * 100"
    }
   ]
  },
  {
   "title": "Requests Errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (haproxy_frontend_request_errors_total{task_name=\"$task_name\",frontend!=\"stats\"})"
    }
   ]
  },
  {
   "title": "Requests Denied",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (haproxy_frontend_requests_denied_total{task_name=\"$task_name\",frontend!=\"stats\"})"
    }
   ]
  },
  {
   "title": "Bytes Incoming",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 24 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(haproxy_frontend_bytes_in_total{task_name=\"$task_name\",frontend!=\"stats\"}[1m]))"
    }
   ]
  },
  {
   "title": "Bytes Outgoing",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 24 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(haproxy_frontend_bytes_out_total{task_name=\"$task_name\",frontend!=\"stats\"}[1m]))"
    }
   ]
  },
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Response Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 28 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "max (haproxy_backend_http_response_time_average_seconds{task_name=\"$task_name\",backend!=\"stats\"})"
    }
   ]
  },
  {
   "title": "Queue Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 28 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "max (haproxy_backend_http_queue_time_average_seconds{task_name=\"$task_name\",backend!=\"stats\"})"
    }
   ]
  },
  {
   "title": "Total responses by HTTP code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(haproxy_backend_http_responses_total{task_name=\"$task_name\",frontend!=\"stats\"}) by (code)",
     "legendFormat": "Backend {{ code }}"
    }
   ]
  },
  {
   "title": "Response Errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (haproxy_backend_response_errors_total{task_name=\"$task_name\",backend!=\"stats\"})"
    }
   ]
  },
  {
   "title": "Connection Errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (haproxy_backend_connection_errors_total{task_name=\"$task_name\",backend!=\"stats\"})"
    }
   ]
  },
  {
   "title": "Current Queue",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(haproxy_backend_current_queue{task_name=\"$task_name\",backend!=\"stats\"}[1m]))"
    }
   ]
  },
  {
   "title": "Redispatch Warnings",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (haproxy_backend_redispatch_warnings_total{task_name=\"$task_name\",backend!=\"stats\"})"
    }
   ]
  }
 ]
}